import blockContent from './blockContent'
import cta from './cta'
import faq from './faq'
import heroSection from './heroSection'
import popUp from './popUp'
import service from './service'
import testimonial from './testimonial'
import whyChooseUs from './whyChooseUs'
import VideoCTA from './VideoCTA'
import privacyPolicy from './privacyPolicy'
import calculator from './calculator'
import cookiePolicy from './cookiePolicy'
import header_testimonial from './header_testimonial'
import header_whyChooseUs from './header_WhyChooseUs'
import plagiarismPolicy from './plagiarismPolicy'
import refundPolicy from './refundPolicy'
import terms_Condition from './terms_Condition.js'
import footer from './footer.js'
import service_post from './service_post'
import blog_post from './blog_post'


export const schemaTypes = [service_post, blog_post, blockContent, popUp, faq, service, whyChooseUs, heroSection, testimonial, cta, VideoCTA, privacyPolicy, refundPolicy, calculator, plagiarismPolicy, cookiePolicy, header_testimonial, header_whyChooseUs, terms_Condition, footer]
